# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Clone Look-Into-Person fork
        run: |
          git clone https://github.com/sloanlipman/Look-Into-Person.git app/process/segnet
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Download model
        run: |
          mkdir app/process/segnet/models
          wget https://github.com/sloanlipman/Look-Into-Person/releases/download/v1.1/model.11-0.8409.hdf5 && mv model.11-0.8409.hdf5 ./app/process/segnet/models/
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f app/process/segnet/requirements.txt ]; then pip install -r app/process/segnet/requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=app/process/segnet
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=app/process/segnet
      - name: Test with pytest
        run: python3 -m pytest
